// <auto-generated />
using System;
using InvitesBlog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvitesBlog.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905121637_DropBucketTitleAndCover")]
    partial class DropBucketTitleAndCover
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvitesBlog.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneE164")
                        .HasColumnType("text")
                        .HasColumnName("phone_e164");

                    b.Property<string>("ThemePreference")
                        .HasColumnType("text")
                        .HasColumnName("theme_preference");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("PhoneE164")
                        .IsUnique()
                        .HasDatabaseName("idx_users_phone_e164");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessTokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CustomContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_content_json");

                    b.Property<string>("DashboardTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("dashboard_token_hash");

                    b.Property<string>("DeliverySettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("delivery_settings_json");

                    b.Property<decimal>("DesignerFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("designer_fee");

                    b.Property<string>("DesignerFeeName")
                        .HasColumnType("text")
                        .HasColumnName("designer_fee_name");

                    b.Property<DateTimeOffset?>("EventEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_end_at");

                    b.Property<DateTimeOffset>("EventStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_start_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<bool>("HasDesignerDiscount")
                        .HasColumnType("boolean")
                        .HasColumnName("has_designer_discount");

                    b.Property<Guid?>("InviterId")
                        .HasColumnType("uuid")
                        .HasColumnName("inviter_id");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sensitive");

                    b.Property<int>("PaidInviteCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("paid_invite_capacity");

                    b.Property<DateTimeOffset?>("PhotosNotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("photos_notified_at");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("retention_days");

                    b.Property<string>("RolesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{\"roles\":[]}")
                        .HasColumnName("roles_json");

                    b.Property<string>("RsvpQuestionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{\"questions\":[]}")
                        .HasColumnName("rsvp_questions_json");

                    b.Property<string>("RulesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rules_json");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("TemplateManifestJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("template_manifest_json");

                    b.Property<string>("TemplatePackageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("template_package_url");

                    b.Property<string>("TemplateVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_version");

                    b.Property<string>("ThemeOverridesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("theme_overrides_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccessTokenHash")
                        .IsUnique()
                        .HasDatabaseName("idx_campaigns_access_token_hash");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("idx_campaign_created_by");

                    b.HasIndex("DashboardTokenHash")
                        .HasDatabaseName("idx_campaigns_dashboard_token_hash");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_campaigns_status");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.CampaignAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Slot")
                        .HasColumnType("text")
                        .HasColumnName("slot");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("campaign_assets", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.CustomTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<decimal?>("CommissionPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("commission_price");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("DesignerConsentToPublish")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("designer_consent_to_publish");

                    b.Property<Guid>("DesignerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("designer_user_id");

                    b.Property<string>("Html")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("manifest_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PackageUrl")
                        .HasColumnType("text")
                        .HasColumnName("package_url");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_image_url");

                    b.Property<Guid?>("PublishedTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_template_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("RequestedByEmail")
                        .HasColumnType("text")
                        .HasColumnName("requested_by_email");

                    b.Property<bool>("RequesterConsentToPublish")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requester_consent_to_publish");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("UsagePrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("usage_price");

                    b.HasKey("Id");

                    b.HasIndex("DesignerUserId")
                        .HasDatabaseName("idx_custom_templates_designer_user_id");

                    b.HasIndex("Slug")
                        .HasDatabaseName("idx_custom_templates_slug");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_custom_templates_queue");

                    b.ToTable("custom_templates", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("InviteId")
                        .HasColumnType("uuid")
                        .HasColumnName("invite_id");

                    b.Property<bool>("IsOtp")
                        .HasColumnType("boolean")
                        .HasColumnName("is_otp");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text")
                        .HasColumnName("provider_message_id");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_address");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("InviteId")
                        .HasDatabaseName("idx_delivery_invite_id");

                    b.ToTable("delivery_attempts", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.EventPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BucketId")
                        .HasColumnType("uuid")
                        .HasColumnName("bucket_id");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("GuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_url");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("ThumbUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumb_url");

                    b.Property<string>("UploaderName")
                        .HasColumnType("text")
                        .HasColumnName("uploader_name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("BucketId", "DeletedAt", "CreatedAt");

                    b.HasIndex("CampaignId", "DeletedAt", "CreatedAt");

                    b.ToTable("event_photos", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("OptedOut")
                        .HasColumnType("boolean")
                        .HasColumnName("opted_out");

                    b.Property<string>("PhoneE164")
                        .HasColumnType("text")
                        .HasColumnName("phone_e164");

                    b.Property<string>("PhoneRaw")
                        .HasColumnType("text")
                        .HasColumnName("phone_raw");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("idx_guests_campaign_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_guests_email");

                    b.HasIndex("PhoneE164")
                        .HasDatabaseName("idx_guests_phone_e164");

                    b.ToTable("guests", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.Inquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedDesignerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_designer_user_id");

                    b.Property<DateTimeOffset?>("AttendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attended_at");

                    b.Property<string>("Colors")
                        .HasColumnType("text")
                        .HasColumnName("colors");

                    b.Property<decimal?>("CommissionPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("commission_price");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("HasAttended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_attended");

                    b.Property<Guid?>("IssuedTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_template_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Occasion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("occasion");

                    b.Property<string>("References")
                        .HasColumnType("text")
                        .HasColumnName("references");

                    b.Property<Guid?>("RequestedDesignerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_designer_user_id");

                    b.Property<bool>("TemplateIssued")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("template_issued");

                    b.Property<DateTimeOffset?>("TemplateIssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("template_issued_at");

                    b.Property<decimal?>("UsagePrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("usage_price");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDesignerUserId")
                        .HasDatabaseName("idx_inquiries_assigned_designer");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_inquiries_email");

                    b.HasIndex("RequestedDesignerUserId")
                        .HasDatabaseName("idx_inquiries_requested_designer");

                    b.HasIndex("HasAttended", "CreatedAt")
                        .HasDatabaseName("idx_inquiries_queue");

                    b.ToTable("inquiries", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_id");

                    b.Property<bool>("RequiresOtp")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_otp");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<int>("RsvpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("rsvp_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("ViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_at");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("idx_invites_campaign_id");

                    b.HasIndex("GuestId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("idx_invites_token_hash");

                    b.ToTable("invites", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.InviteTrustedIp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<Guid>("InviteId")
                        .HasColumnType("uuid")
                        .HasColumnName("invite_id");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.HasKey("Id");

                    b.HasIndex("InviteId", "IpAddress")
                        .IsUnique()
                        .HasDatabaseName("idx_invite_trusted_ips_invite_ip");

                    b.ToTable("invite_trusted_ips", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.Inviter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingCountry")
                        .HasColumnType("text")
                        .HasColumnName("billing_country");

                    b.Property<string>("BillingName")
                        .HasColumnType("text")
                        .HasColumnName("billing_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Organization")
                        .HasColumnType("text")
                        .HasColumnName("organization");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_e164");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_inviters_email");

                    b.ToTable("inviters", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.MediaBucket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<long>("CapacityBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("capacity_bytes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_date");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset?>("TermEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("term_end_at");

                    b.Property<DateTimeOffset?>("TermStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("term_start_at");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UsedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("used_bytes");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .IsUnique()
                        .HasDatabaseName("idx_media_buckets_campaign")
                        .HasFilter("campaign_id IS NOT NULL");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("media_buckets", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.MediaBucketQr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowAnonymous")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_anonymous");

                    b.Property<Guid>("BucketId")
                        .HasColumnType("uuid")
                        .HasColumnName("bucket_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("ScanCount")
                        .HasColumnType("integer")
                        .HasColumnName("scan_count");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<string>("TokenHint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hint");

                    b.Property<int>("UploadCount")
                        .HasColumnType("integer")
                        .HasColumnName("upload_count");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("idx_media_bucket_qr_token");

                    b.HasIndex("BucketId", "CreatedAt");

                    b.ToTable("media_bucket_qrs", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("PhoneE164")
                        .HasColumnType("text")
                        .HasColumnName("phone_e164");

                    b.Property<int>("Purpose")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("Email", "ExpiresAt")
                        .HasDatabaseName("idx_otp_email_expires");

                    b.HasIndex("PhoneE164", "ExpiresAt")
                        .HasDatabaseName("idx_otp_phone_expires");

                    b.ToTable("otp_challenges", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<int>("InviteCount")
                        .HasColumnType("integer")
                        .HasColumnName("invite_count");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderPaymentId")
                        .HasColumnType("text")
                        .HasColumnName("provider_payment_id");

                    b.Property<string>("ProviderSessionId")
                        .HasColumnType("text")
                        .HasColumnName("provider_session_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ProviderSessionId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_permissions_name");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("ProviderRefundId")
                        .HasColumnType("text")
                        .HasColumnName("provider_refund_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("refunds", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.RsvpResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("answers_json");

                    b.Property<string>("ArrivalTime")
                        .HasColumnType("text")
                        .HasColumnName("arrival_time");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("ContactNote")
                        .HasColumnType("text")
                        .HasColumnName("contact_note");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("GuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count");

                    b.Property<Guid>("InviteId")
                        .HasColumnType("uuid")
                        .HasColumnName("invite_id");

                    b.Property<string>("MealPreference")
                        .HasColumnType("text")
                        .HasColumnName("meal_preference");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("InviteId");

                    b.ToTable("rsvp_responses", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.SuppressionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_hash");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id");

                    b.HasIndex("ContactHash")
                        .IsUnique()
                        .HasDatabaseName("idx_suppression_contact");

                    b.ToTable("suppression_list", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedEmail")
                        .HasColumnType("text")
                        .HasColumnName("assigned_email");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<decimal?>("CommissionPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("commission_price");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("DesignerConsentToPublish")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("designer_consent_to_publish");

                    b.Property<Guid?>("DesignerInviterId")
                        .HasColumnType("uuid")
                        .HasColumnName("designer_inviter_id");

                    b.Property<string>("DesignerName")
                        .HasColumnType("text")
                        .HasColumnName("designer_name");

                    b.Property<Guid?>("DesignerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("designer_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("manifest_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PackageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_url");

                    b.Property<string>("PreviewAnimationUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_animation_url");

                    b.Property<string>("PreviewImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preview_image_url");

                    b.Property<string>("RequestedByEmail")
                        .HasColumnType("text")
                        .HasColumnName("requested_by_email");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<bool>("RequesterConsentToPublish")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requester_consent_to_publish");

                    b.Property<string>("SceneJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scene_json");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("UsagePrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("usage_price");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Public")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("AssignedEmail")
                        .HasDatabaseName("idx_templates_assigned_email");

                    b.HasIndex("DesignerUserId")
                        .HasDatabaseName("idx_templates_designer_user_id");

                    b.HasIndex("Slug")
                        .HasDatabaseName("idx_templates_slug");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.TemplateAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("template_assets", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.TemplateType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("idx_template_types_slug");

                    b.ToTable("template_types", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.UploadedGuestFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultCountry")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_country");

                    b.Property<int>("Duplicates")
                        .HasColumnType("integer")
                        .HasColumnName("duplicates");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<int>("InvalidRows")
                        .HasColumnType("integer")
                        .HasColumnName("invalid_rows");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.Property<int>("ValidRows")
                        .HasColumnType("integer")
                        .HasColumnName("valid_rows");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("uploaded_guest_files", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.UserExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalSubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_subject_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ExternalSubjectId")
                        .IsUnique()
                        .HasDatabaseName("idx_user_external_logins_provider_subject");

                    b.ToTable("user_external_logins", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.VerifiedContactLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_e164");

                    b.Property<string>("VerifiedFrom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verified_from");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_vcl_email");

                    b.HasIndex("PhoneE164")
                        .HasDatabaseName("idx_vcl_phone");

                    b.HasIndex("Email", "PhoneE164")
                        .IsUnique()
                        .HasDatabaseName("idx_vcl_pair");

                    b.ToTable("verified_contact_links", (string)null);
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("InvitesBlog.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvitesBlog.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.UserExternalLogin", b =>
                {
                    b.HasOne("InvitesBlog.Domain.Entities.AppUser", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("InvitesBlog.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvitesBlog.Domain.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("InvitesBlog.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
